### ISSUE TITLE
Errors when installing against a case-sensitive SQL Server 2016 instance

### ISSUE THREAD

**Issue by LitKnd** [NikoNeugebauer/CISL#15]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Install-CISL throws errors about parameters which were not declared when run against a case sensitive SQL Server 2016 instance.

I was able to fix this by:

``find: @currenttrimmedRGsPerc  replace with: @currentTrimmedRGsPerc``
``find: @currenttrimmedRGs  replace with @currentTrimmedRGs``

I just did this across StoredProcs and saved all the files it changed (it was a couple), and after that was able to install A-OK.

Edit: I am no good at markdown but I think I finally got the capitalization to show up :)

**Comment by NikoNeugebauer** [comment]
Hi Kendra,

thank you very much! I will update the code this week or feel free to update the source code as well !

Best regards,
Niko

**Comment by NikoNeugebauer** [comment]
This issue has been fixed & checked into the upcoming 1.5.0 release.
Thank you for reporting!
