### ISSUE TITLE
cstore_doMaintenance @IndexName variable retaining previous value

### ISSUE THREAD

**Issue by suggy1982** [NikoNeugebauer/CISL#18]
It's possible for the @IndexName variable to retain the previous value and therefore it will fail when trying to rebuild an index on a table where the index doesn't exist.

If the results of the following code return nothing e.g. if the table contain only open row groups then when the @IndexName variable is assigned in the next statement it would retain it's previous value.

```
		-- Obtain Columnstore logical fragmentation information
		insert into #Fragmentation
			exec cstore_GetFragmentation @objectId = @objectId, @showPartitionStats = 1;
		select 'objectid - ' + CAST(@objectId AS VARCHAR(50))
		-- Obtain the name of the Columnstore index we are working with

		select @indexName = IndexName
			from #Fragmentation
			where TableName = @currentTableName
```

This can be corrected by assigning a NULL value to the variable first

```
		-- Obtain the name of the Columnstore index we are working with

		SET @indexName = NULL
		select @indexName = IndexName
			from #Fragmentation
			where TableName = @currentTableName
```

**Comment by NikoNeugebauer** [comment]
Good Catch, suggy1982! Thank you!
Faced it yesterday and the fix will be committed to the GitHub very soon - it is a part of the conversion to the Central Repository.
